### PR TITLE
BUS_DOWN_WARNING handler added

### PR DESCRIPTION
**Pull request by cooperqb**
This change is [Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5)

### CODE REVIEW

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
I would like to see a timeout rather than having no way to turn logger back on, I think a good way to do this would be to change the variable name to `logger_off` and when we see the bus down warning set it to something like 40. Then in your main loop, inside the code that runs every 500ms, subtract one from `logger_off` if its greater than zero. That means we would have 20 seconds of being disabled before (if we say abort the bus power off for some reason) we start logging again.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5#-:-N3e48pXEbNQa-fZk_ww:b-h6l0qp)* status: all files reviewed, 3 unresolved discussions (waiting on @cooperqb and @KavinSatheeskumar)

___
*[`main.c` line 18 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5#-N3e3P3s3lPiv7MzkTKd:-N3e3P3t3mrJ43CqOKoJ:bd8r4dn) ([raw file](https://github.com/waterloo-rocketry/cansw_logger/blob/5d1c51ef4fd545719e51934bea863f18500452e7/main.c#L18)):*
> ```C
> #include <stdbool.h>
> 
> static bool logger_on = 1;
> ```

I don't think you need to make a global variable `static`?
___
*[`main.c` line 26 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5#-N3e3TsH-nix3-mYwjUH:-N3e3TsH-nix3-mYwjUI:bngrw99) ([raw file](https://github.com/waterloo-rocketry/cansw_logger/blob/5d1c51ef4fd545719e51934bea863f18500452e7/main.c#L26)):*
> ```C
>     switch (get_message_type(message)) {
>         // Declare this outside of switch statement to prevent errors
>         int cmd_type = -1;
> ```

I thought we were declaring this outside of the switch statement :stuck_out_tongue: (note that you already do).
___
*[`main.c` line 45 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5#-N3e3lQg4y_H2SMoCxlg:-N3e3lQg4y_H2SMoCxlh:bf56rmw) ([raw file](https://github.com/waterloo-rocketry/cansw_logger/blob/5d1c51ef4fd545719e51934bea863f18500452e7/main.c#L45)):*
> ```C
>             break;
>     }
>     handle_can_interrupt(message);
> ```

I think it makes sense to handle `logger_on` here rather than with the heartbeat. If we don't heartbeat it will still fill up buffers and could get messy, this way its just as if there are no CAN messages.

**Comment by cooperqb** [comment]
The static was just to limit the scope of logger_on to this file because I didn't think it was going to be used elsewhere. I can get rid of it if we don't need it though.

**Review by KavinSatheeskumar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5)* status: all files reviewed, 3 unresolved discussions (waiting on @BluCodeGH and @cooperqb)

___
*[`main.c` line 45 at r1](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5#-N3e3lQg4y_H2SMoCxlg:-N3e9s18-AehdfUZZOq7:b33se38) ([raw file](https://github.com/waterloo-rocketry/cansw_logger/blob/5d1c51ef4fd545719e51934bea863f18500452e7/main.c#L45)):*
<details><summary><i>Previously, BluCodeGH (BluCode) wrote…</i></summary><blockquote>

I think it makes sense to handle `logger_on` here rather than with the heartbeat. If we don't heartbeat it will still fill up buffers and could get messy, this way its just as if there are no CAN messages.
</blockquote></details>

More clarification from Jack - 
Instead of calling `handle_can_interrupt(message)` like we do at the end of the function, we should be like the below. Then leave main unchanged.



_Code snippet:_
```C
if (logger_on):
    handle_can_interrupt(message);
```

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
Ah makes sense (click the reviewable button to reply to my comments directly). I'll also note this needs to be tested on hardware before merging.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5#-:-N3eJsip0708cgAWyWju:bv6oz7z)* status: all files reviewed, 2 unresolved discussions (waiting on @cooperqb)

___
*[`main.c` line 18 at r2](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5#-N3eJd5G3wJRZwV3rA8y:-N3eJd5H5g1bqcB2elQ4:bu96602) ([raw file](https://github.com/waterloo-rocketry/cansw_logger/blob/a94b70c3ce7f9cf123907ac6e6a23cee9c71f029/main.c#L18)):*
> ```C
> #include <stdbool.h>
> 
> static int logger_off = -1;
> ```

Using `int` isn't great since the width is platform-specific, best to use `uint8_t` here and have 0 mean "logger is on" rather than -1.

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @cooperqb)

___
*[`main.c` line 91 at r3](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5#-N48Tiwu6yUtzwS3GS1I:-N48Tiwu6yUtzwS3GS1J:bt92z88) ([raw file](https://github.com/waterloo-rocketry/cansw_logger/blob/68ec65d64abd9381aa868c84fb447be1943685b5/main.c#L91)):*
> ```C
>         //Don't log messages while logger_off > 0
>         if(logger_off > 0)
>             logger_off--;
> ```

This should happen inside the last_on_time if statement below, otherwise it will go to 0 almost immediately.

**Review by BluCodeGH — APPROVED** [review]
:lgtm:, but needs to be tested on hardware before merging

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/waterloo-rocketry/cansw_logger/5#-:-N48htIz-T7rpZpk2J5i:b4pyeuz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cooperqb)

**Comment by BluCodeGH** [comment]
Merging comp code.

**Pull request merged**
